language: python
python:
  - 2.7
  - 3.5
  - 3.6

sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython jupyter mkl
  - pip install -r dev-requirements.txt
  - export MPLBACKEND="agg"

# Run test
script:
  - travis_wait 40 pytest $TEST_DIR -v

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n

